### ISSUE TITLE
Load and Display Images from the Internet

### ISSUE THREAD

**Issue by macbookairbookmac** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#43] opened 2023-03-11 02:28 UTC
All about application is work perfectly unless my loading_img.xml, it is not moving around on my android device over loading phase.
Why ?
Realme | Android 11

**Comment by osuleymanova** [comment] 2023-03-20 20:21
Hello @macbookairbookmac,
Thanks for reaching out to us and sharing your concern.
Please provide the requested information(codelab URL, section, steps to reproduce the issue, AS version) to proceed further. Unfortunately the issue will be closed within 7 days if there is no further update.

**Comment by osuleymanova** [comment] 2023-05-23 22:35
The issue is closed as no further clarification provided.

**Closed by osuleymanova** 2023-05-23 22:35 UTC
